doc: Update k8s node pool resource version
Just tried to use the node pool verbatim from the docs, got:

```
Error: error creating k8s node pool: 422 Unprocessable Entity {
│   "httpStatus" : 422,
│   "messages" : [ {
│     "errorCode" : "200",
│     "message" : "[VDC-14-1830] Operation cannot be executed because the K8s version 1.18.5 is not viable for nodepools in cluster. Available versions are [1.20.10, 1.21.4, 1.21.9]"
│   } ]
│ }
```

So lets update the version